addons:
  postgresql: "11.3"
before_script:
  - "psql -c 'create database test_jsonate;' -U postgres"
dist: trusty
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
install:
  - "pip install django==${DJANGO} Pillow psycopg2-binary"
  - "pip install ."
services:
  - postgresql
language: python
python:
  - "3.6"
script: "python test_project/manage.py test test_app"
sudo: false
