language: python
python:
  - "3.6"
addons:
  postgresql: "11.3"
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
    matrix:
      exclude:
        - python: "2.7"
          env: DJANGO=2.0
        - python: "2.7"
          env: DJANGO=2.1
install:
  - pip install django==${DJANGO} Pillow psycopg2-binary
  - pip install .
before_script:
  - psql -c 'create database test_jsonate;' -U postgres

script: python test_project/manage.py test test_app
